# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "dereknlp"
repo_name: "arxivpaper-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/nlp-arxiv-daily.json'
json_gitpage_path: './docs/nlp-arxiv-daily-web.json'
json_wechat_path: './docs/nlp-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

keywords:
  "Fake News":
    filters: ["fake news", "Fake news"]
  "Rumour":
    filters: ["rumour", "rumor"]
  "Stance Detection":
    filters: ["Stance Detection"]
  "News Media":
    filters: ["news", "media"]
